### ISSUE TITLE
iCal feed of Node events

### ISSUE THREAD

**Issue by andrew** [knode/node-meatspace#1]
Would be great to be able to subscribe to an iCal feed of all the events that automatically updates, maybe a shared Google Calendar?

**Comment by mikeal** [comment]
How useful would it really be though considering that these events are located all over the world? I certainly couldn't add it to my calendar since the vats majority of them I can't actually attend.

**Comment by andrew** [comment]
Yeah I guess not amazingly useful.

Turns out there is a feed of every event tagged with Node.js on Lanyrd already: http://lanyrd.com/topics/nodejs/

**Comment by mikeal** [comment]
meetup.com might have something similar as well. I used to pull these in to my calendar but, even when just adding local meetups, it was too overwhelming in my calendar.

the main purpose of the calendar in the readme is to share what people are doing, especially some of the less traditional in-person meetups, and to give everyone an idea of just how widely distributed the community is.
