### ISSUE TITLE
Twitter Avatar

### ISSUE THREAD

**Issue by mikeal** [knode/node-meatspace#23]
I registered the twitter account, i need an awesome avatar now :)

Maybe a PUN on meat, @maxogden and @jlord love PUNS :)

**Comment by luk-** [comment]
oh I have a good idea

**Comment by luk-** [comment]
will draw it when i get home unless someone else meats me to it

**Comment by mikeal** [comment]
would also be awesome if it is a favicon for the website :)

**Comment by luk-** [comment]
i will try to meat that requirement

**Comment by mikeal** [comment]
@luk- any update on this?

**Comment by luk-** [comment]
Yeah, sorry, I know I kinda dropped the ball here. I'll finish what I have
and upload later today.

**Comment by luk-** [comment]
I think this captures the spirit of the node community pretty well 

![untitled artwork 2013-10-06 11 38 23-715 pm](https://f.cloud.github.com/assets/62224/1278581/5c2f2444-2f1b-11e3-9425-4ab7b7c6cc3a.png)

**Comment by luk-** [comment]
If you notice, not only is the character a hexagonal hamburger, he also has hamburger feet. I do not know how to draw pants though.

**Comment by stevekinney** [comment]
+1000

Although, it would be great if it had hamburgers for hands as well—just a suggestion.

**Comment by junosuarez** [comment]
> I do not know how to draw pants though.

This might be the one phrase that captures node's true essence.

**Comment by mikeal** [comment]
> I do not know how to draw pants though.

scandalous!

**Comment by stevekinney** [comment]
@luk- Have you considered a hat of some kind? Perhaps a [pork pie](https://en.wikipedia.org/wiki/Pork_pie_hat)?

**Comment by luk-** [comment]
I have considered a spacesuit

**Comment by stevekinney** [comment]
Pantsless spacesuit.
