### ISSUE TITLE
Getting a meetup started

### ISSUE THREAD

**Issue by KathleenLD** [knode/node-meatspace#28]
It looks like #5 covers some of this, but a few months ago I gave a talk called [Mappers in Meatspace](http://vimeopro.com/openstreetmapus/state-of-the-map-us-2013/video/68098498) at the OpenStreetMap US conference. After the fact I realized that it was actually just about how to take online communities (particularly technical ones) and move them offline. 

This obviously isn't at all about node, but if you ignore the OSM-specific stuff it might be relevant to people who are looking to create node meetups. Even if it's not useful, it might be worth adding other "get a meetup started" resources to this project.

**Comment by mikeal** [comment]
Great talk! 

One thing that stands out is "how do you keep a meetup going?"

I'm not a big fan of using meetup.com but one of things it does really well is help you roll the success of a meetup, however big or small, in to the next event.

This could be a thread all of its own :)

**Comment by KathleenLD** [comment]
Yeah, that's definitely the biggest challenge-- at least as big as simply starting a meetup in the first place! There isn't a silver bullet, but some big factors are ensuring you have help (avoid organizer burnout!) and ensuring you've got a sustainable scope (don't commit to running weekly workshops!). I know that some people dislike meetup, but it's definitely one of the most useful tools I think that any organizer can have in his or her back pocket.

**Comment by mcollina** [comment]
A part from logistic issues, for unusual locations (without a **strong** dev community), it is very hard to find speakers. Maybe remote talks, like the ones of Node Dublin can help starting a new one.
