### ISSUE TITLE
Knode collaboration and maintinence changes

### ISSUE THREAD

**Issue by mikeal** [knode/node-meatspace#65]
Heya,

I haven't been great about keep this project up to date all by myself lately. I've now added @phated @hackygolucky and @gergelyke as collaborators.

For reference, this is what I _was_ doing when I was on top of maintaining this.
1. Merge pull requests when they came in. Pull down the change, run the build script locally and push the updated the index.html static file. gh-pages does the rest.
2. Every week move the schedule around a big to highlight _this week_. I'd also troll through what I could find for the next week on meetup.com and add it manually.

I had also originally intended this to be a place for people to go if they wanted to ask questions about running a meetup or get one started. knode has already succeeded much more at that so I think it's a good idea to direct the issues that are here to knode and alter the text on the website to point at knode for resources and support in organizing a new event.

**Comment by hackygolucky** [comment]
!m @mikeal 

This is going to be a cool opportunity to help out these two projects. Will setup calendar reminders for myself to help with the weekly updates.

**Comment by gergelyke** [comment]
Thanks @mikeal , will do our best!
By the way, already done the first update! :)

**Comment by mikeal** [comment]
@gergelyke awesome! FYI, gh-pages can have up to a 10 minute cache lag so don't be surprised if you don't see pushes show up immediately on the website.

**Comment by mikeal** [comment]
@rosskukulinski added

**Comment by rosskukulinski** [comment]
Excited to help out as well (thanks for bringing me on @mikeal)

I'm in the process of bringing BayNode back to life (http://baynode.github.io/) so learning from fellow organizers is important to me.

**Comment by mikeal** [comment]
@hackygolucky would you want to modify the text about "logging issues" to get help and support with meetups to something that introduces and points people towards knode instead?

**Comment by hackygolucky** [comment]
@mikeal Happy to do so! Adding some js conferences now. I'll modify the logging issues as a separate commit.

**Comment by gergelyke** [comment]
:+1:
