### ISSUE TITLE
When we list a Node event, what are we looking for?

### ISSUE THREAD

**Issue by hackygolucky** [knode/node-meatspace#67]
When looking at events that are currently listed, they are most oftentimes clearly named as <something>Node funtimes. Are the events expected to be Node -only- or focused on Node? 

For instance, there are JavaScript conferences that will dedicate a healthy number of talks to Node.js. Should we accept those?

**Comment by gergelyke** [comment]
In my opinion: of course! If the given event has anything to do with Node, then we should accept it.

**Comment by mikeal** [comment]
anything to do with javascript or the web is fine. node is a fairly indispensable aspect of contemporary web development so anything web related is relevant.

**Comment by gergelyke** [comment]
:+1:

**Comment by hackygolucky** [comment]
Sweet. Moving forward with adding more confs. Thanks!
