### ISSUE TITLE
Move repo to knode/node-meatspace

### ISSUE THREAD

**Issue by mikeal** [knode/node-meatspace#78]
GitHub makes this pretty easy and forwards everything relevant.

Any downside?

**Comment by gergelyke** [comment]
Everything should be okay

**Comment by hackygolucky** [comment]
Sounds good to me! +1

**Comment by mikeal** [comment]
It says I don't have admin rights to knode :(

**Comment by hackygolucky** [comment]
Fixing right meow :D

**Comment by mikeal** [comment]
Done, but i don't have write access anymore :( Can we get the Collaborator list back in line?

**Comment by hackygolucky** [comment]
Friggin' weird. Fixing for good.

**Comment by mikeal** [comment]
Cool, anyone who used to have write access but doesn't now, let us know! :)

**Comment by gergelyke** [comment]
"Everything should be okay" - haha, i couldn't be more bad
