### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by hackygolucky** [knode/node-meatspace#82]
Travis build is currently broken. Looking into whether it was moving over the repo or  the automated build(looking at this first). 

https://travis-ci.org/knode/node-meatspace/builds/17104758

Please don't merge the recent PR submissions until this is resolved.

**Comment by phated** [comment]
@hackygolucky Travis builds on PRs too, but doesn't expose the secure keys on PRs (because people could PR code that displayed them), so the authentication fails.

**Comment by hackygolucky** [comment]
Derp. @phated is working on a fix.

**Comment by gergelyke** [comment]
fixed!
